# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cards',
                'doc_host': 'https://hamelsmu.github.io',
                'git_url': 'https://github.com/hamelsmu/cards',
                'lib_path': 'cards'},
  'syms': { 'cards.card': { 'cards.card.Card': ('card.html#card', 'cards/card.py'),
                            'cards.card.Card.__init__': ('card.html#card.__init__', 'cards/card.py'),
                            'cards.card.Card.__lt__': ('card.html#card.__lt__', 'cards/card.py'),
                            'cards.card.Card.__repr__': ('card.html#card.__repr__', 'cards/card.py')},
            'cards.core': {'cards.core.foo': ('core.html#foo', 'cards/core.py')},
            'cards.deck': { 'cards.deck.Deck': ('deck.html#deck', 'cards/deck.py'),
                            'cards.deck.Deck.__init__': ('deck.html#deck.__init__', 'cards/deck.py'),
                            'cards.deck.Deck.__repr__': ('deck.html#deck.__repr__', 'cards/deck.py')}}}
