# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_deck.ipynb.

# %% auto 0
__all__ = ['Deck']

# %% ../nbs/01_deck.ipynb 2
from .card import Card, ranks, suits

# %% ../nbs/01_deck.ipynb 3
class Deck:
    """
    A collection of `Card`s.
    """
    def __init__(self):
        self.cards = []
        for suit in range(len(suits)):
            for rank in range(1, len(ranks)):
                self.cards.append(Card(suit, rank))
    
    def __repr__(self):
        return " ".join(repr(card) for card in self.cards)
